server:
  port: 1112

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/

spring:
  application:
    name: eureka-server
