server:
  port: 1111

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer2:1112/eureka/

spring:
  application:
    name: eureka-server
